name: jlab
channels:
  - default
  - conda-forge
dependencies:
  - jupyterlab>=3.2
  - ipykernel
  - pip
  - pip:
      - jupyterlab-recents
      - jlab-enhanced-launcher
      - jupyterlab-git
      - jupyterlab-favorites
