{% set name = "jlab" %}
{% set version = "1.1" %}

package:
  name: "{{ name }}" 
  version: "{{ version }}"

requirements:
  run:
    - jupyterlab>=3.2
    - ipykernel
    - pip
    - jupyterlab-recents
    - jlab-enhanced-launcher
    - jupyterlab-git
    - jupyterlab-favorites
    - conda-forge::nodejs


about:
  home: https://github.com/vuillaut/myenvs/
  license: MIT Licence
  summary: "Personnal jupyter-lab environment with extensions"
  
extra:
  recipe-maintainers:
    - vuillaut

