{% set name = "jlab-mpl" %}
{% set version = "1.0" %}

package:
  name: "{{ name }}" 
  version: "{{ version }}"

requirements:
  run:
    - vuillaut::jlab
    - ipympl
    - conda-forge::nodejs
    - conda-forge/label/gcc7::nodejs
    - conda-forge/label/cf201901::nodejs
    - conda-forge/label/cf202003::nodejs

about:
  home: https://github.com/vuillaut/myenvs/
  license: MIT Licence
  summary: "Personnal jupyter-lab environment with extensions"
  
extra:
  recipe-maintainers:
    - vuillaut

