name: publish_conda

on: push
#  release:
#    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        subDir: 'lstchain-v0.8.2.post1'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
