name: publish_conda

on: push
#  release:
#    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subDir: 'sci'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
